s="http://sports.sina.com.cn/"
a=s.count("t")
b=s.find("com")
c=s.replace(".","-")
d=2
e=s[7:13]
f=s[14:18]
g=s[-12:-8]
h=s[-19:-13]
i=s.upper()
j=len(s)
k=s+"index"
print("(1)字符串中字母t出现的次数：",a)
print("(2)字符串中com子字符串出现在：",b+1,"-",b+3,"位")
print("(3)",c)
print("(4)正向切片：",e,f,"反向切片：",g,h)
print("(5)",i)
print("(6)字符串的总字符个数:",j)
print("(7)",k)
